services:
  frontend:
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    container_name: mgp-frontend
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    container_name: mgp-backend
    environment:
      - NODE_ENV=production
      - PORT=4000
    volumes:
      - ./backend:/app
      - /app/node_modules
    # depends_on:
    #   - db

  # db:

  nginx:
    image: nginx:alpine
    container_name: mgp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./mgp-nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    container_name: mgp-certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM;
       while :; do
         certbot renew --webroot -w /var/lib/letsencrypt --quiet;
         sleep 12h & wait $${!};
       done"


volumes:
  mgp-data:
  certbot-etc:
  certbot-var: